version: '3.3'
services:
  nginx:
    image: nginx:latest
    container_name: "nginx"
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "80:80"
      - "443:443"
    restart: always
    working_dir: /var/www
    volumes:
      - ./../:/var/www
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx:/var/log/nginx
      - /etc/hosts:/etc/hosts:ro
    depends_on:
      - fpm-56
      - fpm-70
      - fpm-71
      - fpm-72
      - fpm-73
      - fpm-74
      - fpm-80
    networks:
      global-default:

  fpm-56:
    image: silvanei/php:5.6-fpm
    container_name: "5.6-fpm"
    env_file:
      - .env
    restart: always
    working_dir: /var/www
    volumes:
      - ./php/40-custom.ini:/usr/local/etc/php/conf.d/9999-custom.ini
      - ./php/40-xdebug2.ini:/usr/local/etc/php/conf.d/9999-xdebug2.ini
      - ./../:/var/www
      - /etc/hosts:/etc/hosts:ro
    networks:
      global-default:

  fpm-70:
    image: silvanei/php:7.0-fpm
    container_name: "7.0-fpm"
    env_file:
      - .env
    restart: always
    working_dir: /var/www
    volumes:
      - ./php/40-custom.ini:/usr/local/etc/php/conf.d/9999-custom.ini
      - ./php/40-xdebug2.ini:/usr/local/etc/php/conf.d/9999-xdebug2.ini
      - /tmp:/tmp
      - /etc/hosts:/etc/hosts:ro
    networks:
      global-default:

  fpm-71:
    image: silvanei/php:7.1-fpm
    container_name: "7.1-fpm"
    env_file:
      - .env
    restart: always
    working_dir: /var/www
    volumes:
      - ./php/40-custom.ini:/usr/local/etc/php/conf.d/9999-custom.ini
      - ./php/40-xdebug2.ini:/usr/local/etc/php/conf.d/9999-xdebug2.ini
      - ./../:/var/www
      - /etc/hosts:/etc/hosts:ro
    networks:
      global-default:

  fpm-72:
    image: silvanei/php:7.2-fpm
    container_name: "7.2-fpm"
    env_file:
      - .env
    restart: always
    working_dir: /var/www
    volumes:
      - ./php/40-custom.ini:/usr/local/etc/php/conf.d/9999-custom.ini
      - ./php/40-xdebug3.ini:/usr/local/etc/php/conf.d/9999-xdebug3.ini
      - ./../:/var/www
      - /etc/hosts:/etc/hosts:ro
    networks:
      global-default:

  fpm-73:
    image: silvanei/php:7.3-fpm
    container_name: "7.3-fpm"
    env_file:
      - .env
    restart: always
    working_dir: /var/www
    volumes:
      - ./php/40-custom.ini:/usr/local/etc/php/conf.d/9999-custom.ini
      - ./php/40-xdebug3.ini:/usr/local/etc/php/conf.d/9999-xdebug3.ini
      - ./../:/var/www
      - /etc/hosts:/etc/hosts:ro
    networks:
      global-default:

  fpm-74:
    image: silvanei/php:7.4-fpm
    container_name: "7.4-fpm"
    env_file:
      - .env
    restart: always
    working_dir: /var/www
    volumes:
      - ./php/40-custom.ini:/usr/local/etc/php/conf.d/9999-custom.ini
      - ./php/40-xdebug3.ini:/usr/local/etc/php/conf.d/9999-xdebug3.ini
      - ./../:/var/www
      - /etc/hosts:/etc/hosts:ro
    networks:
      global-default:

  fpm-80:
    image: silvanei/php:8.0-fpm
    container_name: "8.0-fpm"
    env_file:
      - .env
    restart: always
    working_dir: /var/www
    volumes:
      - ./php/40-custom.ini:/usr/local/etc/php/conf.d/9999-custom.ini
      - ./php/40-xdebug3.ini:/usr/local/etc/php/conf.d/9999-xdebug3.ini
      - ./../:/var/www
      - /etc/hosts:/etc/hosts:ro
    networks:
      global-default:

  portainer:
    image: portainer/portainer-ce:alpine
    container_name: "portainer"
    restart: always
    ports:
      - "81:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      global-default:

volumes:
  portainer_data:

networks:
  global-default:
    external: true