version: '3.3'
services:
  rabbitmq.docker.local:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq:5672
    env_file:
      - ./../.env
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      global-default:

networks:
  global-default:
    external: true