version: '3.3'
services:
  postgress.docker.local:
    image: postgres:14.1-alpine3.14
    container_name: postgres
    env_file:
      - ./../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      global-default:

volumes:
  postgres_data:

networks:
  global-default:
    external: true